version: 2

updates:
  # Check for updates to GitHub Actions every month.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    assignees:
      - jlucktay
    groups:
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 1
    reviewers:
      - jlucktay

  # Check for updates to Go modules every month.
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
    assignees:
      - jlucktay
    groups:
      go:
        patterns:
          - '*'
    open-pull-requests-limit: 1
    reviewers:
      - jlucktay
