builds:
  - flags:
      - -trimpath
      - -v

    ldflags:
      - >
        -X 'go.jlucktay.dev/version.buildDate={{ .Date }}'
        -X 'go.jlucktay.dev/version.builtBy=GoReleaser'
        -X 'go.jlucktay.dev/version.commit={{ .ShortCommit }}'
        -X 'go.jlucktay.dev/version.executable={{ .ProjectName }}'
        -X 'go.jlucktay.dev/version.version={{ .Version }}'

    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    # Set the modified timestamp on the output binary, typically you would do this to ensure a build was reproducible.
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - replacements:
      "386": i386
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows

snapshot:
  name_template: "{{ incpatch .Version }}-next"

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
