before:
  hooks:
    - go mod download

builds:
  - main: ./

    flags:
      - -v

    env:
      - CGO_ENABLED=0

    ldflags:
      - >
        -s -w
        -X 'go.jlucktay.dev/goppuku/cmd.version={{ .Version }}'
        -X 'go.jlucktay.dev/goppuku/cmd.commit={{ .ShortCommit }}'
        -X 'go.jlucktay.dev/goppuku/cmd.date={{ .Date }}'
        -X 'go.jlucktay.dev/goppuku/cmd.builtBy=GoReleaser'

changelog:
  sort: asc
