name: Auto approve Dependabot

on: pull_request

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve Dependabot
        uses: cognitedata/auto-approve-dependabot-action@v2.0.0
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
