name: Dependabot auto-merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  dependabot:
    if: github.actor == 'dependabot[bot]'

    runs-on: ubuntu-latest

    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
