name: goreleaser

on:
  push:
    tags:
      - v*

permissions:
  contents: write

# Concurrency ensures that only a single workflow using the same concurrency group will run at a time.
# When a workflow is queued in the same repository and concurrency group, any workflow in progress will be cancelled.
# This concurrency group is keyed to the 'ref' property in the 'github' context, to map back to the branch/tag that
# triggered this workflow run.
concurrency:
  cancel-in-progress: true
  group: release_${{ github.ref }}

jobs:
  check-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Check out ${{ github.repository }} - all history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Confirm that the 'main' branch contains the '${{ github.ref }}' tag
        run: >
          git branch --all --contains '${{ github.ref }}' --no-column --format='%(refname)'
          | grep -c '\/main$'

  goreleaser:
    runs-on: ubuntu-latest

    needs:
      - check-tag

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
